name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stats
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: theSnackOverflow
          filename: metrics-stats.svg
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Asia/Seoul
          config_animations: yes

      - name: Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: theSnackOverflow
          filename: metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_languages_details: percentage, bytes-size
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 14
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          config_timezone: Asia/Seoul
